spring.application.name=SafeZoneBackend
server.port=8080
spring.cloud.azure.cosmos.endpoint=""
spring.cloud.azure.cosmos.key=""
spring.cloud.azure.cosmos.database=SafeZone
spring.cloud.azure.cosmos.populate-query-metrics=false
# ?? Logs ????????????????????????????????????????????????????????
# WARN para Azure (muy verboso por defecto)
logging.level.com.azure.cosmos=WARN
logging.level.com.azure.core=WARN
# INFO para tu código
logging.level.SafeZone=INFO

jwt.secret=d7a4f81c9e3b6205fa81bc3d4e7f9021aeb3c45d

