spring.application.name=SafeZoneBackend
server.port=8080

spring.cloud.azure.cosmos.endpoint=${COSMOS_ENDPOINT}
spring.cloud.azure.cosmos.key=${COSMOS_KEY}
spring.cloud.azure.cosmos.database=${COSMOS_DATABASE}
spring.cloud.azure.cosmos.populate-query-metrics=false
spring.cloud.azure.cosmos.direct-connection.enabled=false

logging.level.com.azure.cosmos=WARN
logging.level.com.azure.core=WARN
logging.level.SafeZone=INFO

jwt.secret=${JWT_SECRET}
safezone.panic.neutral-redirect-url=https://www.google.com